apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: nfs-storage
      mountPath: /usr/share/nginx/html

  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
